version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 -m virtualenv .
      - run: source bin/activate
      - run: pip install -r requirements.txt
      - run: python notificationsuppression/suppression.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 -m virtualenv .
      - run: source bin/activate
      - run: pip install -r requirements.txt
      - run: python notificationsuppression/suppressiontest.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build